# Generated by Django 5.2 on 2025-04-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Texto de la pregunta'),
        ),
    ]
